ALTER TABLE addresses ADD COLUMN IF NOT EXISTS address_type VARCHAR(20) DEFAULT 'Home';
ALTER TABLE addresses ADD COLUMN IF NOT EXISTS house_number VARCHAR(50) DEFAULT NULL;
ALTER TABLE addresses ADD COLUMN IF NOT EXISTS floor_number VARCHAR(50) DEFAULT NULL;
